# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

writeFile <- function(parent, xmlText, parentEnd, R_fileName) {
    .Call('opendocx_writeFile', PACKAGE = 'opendocx', parent, xmlText, parentEnd, R_fileName)
}

